# Generated by Django 4.2.7 on 2023-11-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
